### ISSUE TITLE
quoteKeys优化

### ISSUE THREAD

**Issue by wu529778790** [ctq123/du-i18n#3]
```json
"quoteKeys": ["this.$t", "$t", "i18n.t"]
```
现在的这个this.$t只有在<script>标签里面才会用到，还有一种写法是<script setup>，这种就需要用i18n.t

我如果配置成  "quoteKeys": ["i18n.t", "$t", "i18n.t"], 就不会自动写入import i18n from '@/i18n'

单独的js或者ts是没有问题。

尝试fork仓库修改，遇到以下问题

不删除yarn.lock文件，下载卡死。删除lock文件，打包报错。能说下node版本么？

我期望的这个配置选项是，
```json
script: this.$t,
script setup: i18n.t // 而且这个会自动引入
js: i18n.t // 也会自动引入 
```

看来源码里面的配置是
```js
const replaceKey = quoteKeys.length > 2 ? quoteKeys[1] : quoteKeys[0];
```

**Comment by ctq123** [comment]
fork后应该解决了吧
